steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', './...']
  env: ['PROJECT_ROOT=github.com/metal-tile/godeye']
- name: 'gcr.io/cloud-builders/go'
  args: ['generate']
  env: ['PROJECT_ROOT=github.com/metal-tile/godeye']
- name: 'gcr.io/cloud-builders/go'
  args: ['test', '.']
  env: ['PROJECT_ROOT=github.com/metal-tile/godeye']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '-a', '-ldflags', "'-s'", '-installsuffix', 'cgo', 'github.com/metal-tile/godeye']
  env: [
    'PROJECT_ROOT=github.com/metal-tile/godeye',
    'CGO_ENABLED=0',
    'GOOS=linux'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/metal-tile/godeye/$BRANCH_NAME:$COMMIT_SHA', '.']

images: ['gcr.io/$PROJECT_ID/metal-tile/godeye/$BRANCH_NAME:$COMMIT_SHA']